version: "3.8"
services:
  ssh:
    build: ./
    ports:
      - "10022:22"
    volumes:
      - ./:/tmp/drl
    command:
      - /usr/sbin/sshd
      - -D

  jupyter:
#    image: jupyter/tensorflow-notebook
    build: ./
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - ./:/tf/drl
    ports:
      - "18888:8888"
    command:
      - bash
      - -c
      - source /etc/bash.bashrc && jupyter lab --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.password='sha1:4bded1508ac7:a6b52cadfc342ca8dbe84c6a9d9cf5efcec47d56' # Password: drl

  tensorboard:
    build: ./
    volumes:
      - ./:/tf/drl
    ports:
      - "16006:6006"
    command:
      - bash
      - -c
      - source /etc/bash.bashrc && tensorboard --logdir /tf/drl/notebooks/data --host 0.0.0.0 # Password: drl